-- Создание таблицы mood_entries
create table if not exists mood_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  mood_level integer check (mood_level >= 1 and mood_level <= 5) not null,
  notes text,
  entry_date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Создание таблицы habits
create table if not exists habits (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  name text not null,
  description text,
  frequency text check (frequency in ('daily', 'weekly')) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Создание таблицы habit_entries
create table if not exists habit_entries (
  id bigint generated by default as identity primary key,
  habit_id bigint references habits(id) on delete cascade not null,
  entry_date date not null,
  completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Добавление индексов для оптимизации запросов
create index if not exists mood_entries_user_id_idx on mood_entries (user_id);
create index if not exists mood_entries_entry_date_idx on mood_entries (entry_date);
create index if not exists habits_user_id_idx on habits (user_id);
create index if not exists habit_entries_habit_id_idx on habit_entries (habit_id);
create index if not exists habit_entries_entry_date_idx on habit_entries (entry_date);